# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrawlStats' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for BrawlStats
  pod 'Charts'

  target 'BrawlStatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BrawlStatsUITests' do
    # Pods for testing
  end

end
